### ISSUE TITLE
keycaps

### ISSUE THREAD

**Issue by geddski** [kiibohd/case#3]
I'm wanting to 3d print some custom keycaps for my ergodox infinity. Do you know where I could find the designs for those?

**Comment by OvahKeel** [comment]
Unfortunately I do not know of anybody who has 3d models for keycaps.

**Comment by abcsds** [comment]
Hey, I know this problem is closed, but I stumbled upon it and got a solution, so I might as well just post it here in case anyone is curious. A really easy solution is simply to google it: here's the first result with 218 models of cherry keycaps for free: https://www.thingiverse.com/thing:2091304

The important thing is you have the (mount)[https://www.thingiverse.com/thing:344133], and you can model your key anyway you want.
